### ISSUE TITLE
Bug when trying to train on CIFAR-100 with ELR

### ISSUE THREAD

**Issue by Alfred-N** [YinengWang/Supervised-Image-Classification-with-Noisy-Labels-Using-Deep-Learning#20]
Ok, I just tried to run on cifar-100 with ELR and got this error. Not sure what is wrong

![image](https://user-images.githubusercontent.com/47230525/118864462-4d0fd380-b8e0-11eb-822c-5ac1625a95ff.png)

**Comment by rlindsberg** [comment]
Which commit?

**Comment by YinengWang** [comment]
It's probably because of wrong number of classes. Did you set `config['classes'] = 100`?

**Comment by alessioGalatolo** [comment]
Above this error you should also see the assertion that failed

**Comment by Alfred-N** [comment]
> It's probably because of wrong number of classes. Did you set `config['classes'] = 100`?
Yes, I forgot we had to manually change classes in config. Thanks! Now it's running
