### ISSUE TITLE
Normalisation for CDON is using normalisation for CIFAR100

### ISSUE THREAD

**Issue by rlindsberg** [YinengWang/Supervised-Image-Classification-with-Noisy-Labels-Using-Deep-Learning#21]
https://github.com/YinengWang/Supervised-Image-Classification-with-Noisy-Labels-Using-Deep-Learning/blob/6c61b62a0a43d2116774c0bd42704b1637ba1b57/datasets.py#L15

**Comment by alessioGalatolo** [comment]
@YinengWang are these good values?
![image](https://user-images.githubusercontent.com/10598113/119252947-220ed380-bbaf-11eb-8672-1fb61e23542a.png)

(https://github.com/YinengWang/ELR/blob/c79a497c9037c0f48e47d0223dc297935dceec7e/ELR/data_loader/data_loaders.py#L58)

**Comment by YinengWang** [comment]
I took these values from @rlindsberg , who computed them
